name: fetch
on: [push]
env:
  REAL_URL: "https://download.pureapk.com/b/XAPK/Y29tLmJ1c2RlLnZpcGxpbmVyXzIwM19lZjc1NGZkMw?as2=153b1ad8f75cb6beb369b4ae2e2901b56c860add&k=2b90bfd7783d8c3f40f060ecece8f4416c860add&_p=Y29tLmJ1c2RlLnZpcGxpbmVy&c=1%7CTRAVEL_AND_LOCAL%7Cb2lkPTkmZGV2PUhFSVNFSSUyMEVOVEVSUFJJU0UlMkNJbmMuJnQ9eGFwayZzPTg2OTE5MjA1JnZuPTEuMS4xJnZjPTIwMw&_fn=VklQJUUzJTgzJUE5JUUzJTgzJUE0JUUzJTgzJThBJUUzJTgzJUJDJUU1JTg1JUFDJUU1JUJDJThGJUUzJTgyJUEyJUUzJTgzJTk3JUUzJTgzJUFBJUUzJTgwJTgwJUUuJUFCJTk4JUUuJTgwJTlGJUUzJTgzJTkwJUUzJTgyJUI5JUUzJTgyJTkyJUU2JTlDJTgwJUU1JUFFJTg5JUU1JTgwJUE0JUUzJTgxJUE3JUU0JUJBJTg4JUU3JUI0JTg0XzEuMS4xX2Fwa2NvbWJvLmNvbS54YXBr"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download XAPK
        run: |
          curl -sSL -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36" -o app.xapk "$REAL_URL"
          ls -la app.xapk
          file app.xapk
      - name: Extract
        run: |
          mkdir -p out && cd out && unzip -o -q ../app.xapk || true
          ls -la
          find . -name "*.apk" -exec ls -la {} \;
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vipliner-apk
          path: out/
          retention-days: 1
          compression-level: 0
